### ISSUE TITLE
Header animation bug when we launch it in a resized window ! 

### ISSUE THREAD

**Issue by KrankerApfel** [KrankerApfel/PROJET_php#1]
I think positions of object drawn in canvas are relative to the window's dimension. So when we launch the animation in a resized windows, it doesn't draw as we wanted 😭 . @pillowinacoma  can you do something ? I put an image to better understand : 
![bug_report00](https://user-images.githubusercontent.com/19972486/38163571-359b4854-34f6-11e8-84d5-486b4fb499dc.png)

**Comment by pillowinacoma** [comment]
the reason why this is happening is actually that most of the variables depend on the canvas size, while the rest is statically defined, i'll try to work more on that and see if i can do it or not ;)

**Comment by pillowinacoma** [comment]
Mostly SOLVED

**Comment by KrankerApfel** [comment]
It's look perfectly good now ! The mouse interaction make it so awesoooooome 👍

**Comment by KrankerApfel** [comment]
Do you wan't me to close the issue or we can use it to speak about header design or anything else about header ?

**Comment by pillowinacoma** [comment]
i like the idea of leaving it to talk about the design and all even if that old thing in there hurts my eyes

**Comment by ghost** [comment]
Coucou !!

**Comment by pillowinacoma** [comment]
@Decim298 Ahh ! Le meilleur est là !!
